name: Publish Npm

on:
  push:
    branch:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo v${{ env.TAG_NAME }}
#      - run: npm ci
#      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}